version: 2
updates:
  # Root package.json
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "09:00"
    open-pull-requests-limit: 5
    reviewers:
      - "typeamp/core-team"
    assignees:
      - "typeamp/devops-team"
    commit-message:
      prefix: "chore(deps)"
      include: "scope"
    labels:
      - "dependencies"
      - "automated"
    allow:
      - dependency-type: "direct"
      - dependency-type: "indirect"

  # Web package dependencies
  - package-ecosystem: "npm"
    directory: "/packages/web"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "09:00"
    open-pull-requests-limit: 5
    reviewers:
      - "typeamp/frontend-team"
    assignees:
      - "typeamp/frontend-team"
    commit-message:
      prefix: "chore(web/deps)"
      include: "scope"
    labels:
      - "dependencies"
      - "frontend"
      - "automated"
    groups:
      # Group React-related updates
      react:
        patterns:
          - "react*"
          - "@types/react*"
      # Group Next.js updates
      nextjs:
        patterns:
          - "next"
          - "@next/*"
      # Group testing dependencies
      testing:
        patterns:
          - "vitest*"
          - "@vitest/*"
          - "@testing-library/*"
          - "jsdom"
      # Group UI/Design dependencies
      ui:
        patterns:
          - "@radix-ui/*"
          - "tailwindcss"
          - "@tailwindcss/*"
          - "lucide-react"
          - "class-variance-authority"
          - "clsx"
          - "tailwind-merge"

  # API package dependencies
  - package-ecosystem: "npm"
    directory: "/packages/api"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "09:00"
    open-pull-requests-limit: 5
    reviewers:
      - "typeamp/backend-team"
    assignees:
      - "typeamp/backend-team"
    commit-message:
      prefix: "chore(api/deps)"
      include: "scope"
    labels:
      - "dependencies"
      - "backend"
      - "automated"
    groups:
      # Group Fastify-related updates
      fastify:
        patterns:
          - "fastify*"
          - "@fastify/*"
      # Group Prisma updates
      prisma:
        patterns:
          - "prisma"
          - "@prisma/*"
      # Group testing dependencies
      testing:
        patterns:
          - "vitest*"
          - "@vitest/*"
          - "supertest"
          - "@types/supertest"
      # Group security dependencies
      security:
        patterns:
          - "bcrypt*"
          - "@types/bcrypt"
          - "jsonwebtoken"
          - "@types/jsonwebtoken"

  # GitHub Actions
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "09:00"
    open-pull-requests-limit: 3
    reviewers:
      - "typeamp/devops-team"
    assignees:
      - "typeamp/devops-team"
    commit-message:
      prefix: "chore(ci)"
      include: "scope"
    labels:
      - "dependencies"
      - "github-actions"
      - "automated"

  # Docker (if applicable)
  - package-ecosystem: "docker"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "09:00"
    open-pull-requests-limit: 2
    reviewers:
      - "typeamp/devops-team"
    assignees:
      - "typeamp/devops-team"
    commit-message:
      prefix: "chore(docker)"
      include: "scope"
    labels:
      - "dependencies"
      - "docker"
      - "automated"