name: Debug CI Issues

on:
  push:
    branches: [main, master, develop, feature/*]
  pull_request:
    branches: [main, master, develop]

jobs:
  debug-environment:
    name: Debug Environment
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'

      - name: Check Node and npm versions
        run: |
          echo "Node version:"
          node --version
          echo "npm version:"
          npm --version

      - name: Install dependencies
        run: npm ci

      - name: Check installed packages
        run: |
          echo "Root packages:"
          npm ls --depth=0
          echo ""
          echo "Web workspace:"
          npm ls --workspace=type --depth=0
          echo ""
          echo "API workspace:"
          npm ls --workspace=@typeamp/api --depth=0

      - name: Check for TypeScript
        run: |
          echo "TypeScript version:"
          npx tsc --version
          echo ""
          echo "Checking if tsconfig files exist:"
          ls -la tsconfig*.json
          ls -la packages/web/tsconfig*.json
          ls -la packages/api/tsconfig*.json

      - name: Test simple TypeScript check
        run: |
          echo "Testing TypeScript on a simple file..."
          echo "const test: string = 'hello';" > test.ts
          npx tsc test.ts --noEmit && echo "✅ TypeScript works!" || echo "❌ TypeScript failed!"
          rm -f test.ts

      - name: Check Prisma setup
        run: |
          echo "Checking Prisma installation:"
          npx prisma --version || echo "Prisma not found!"
          echo ""
          echo "Checking for schema file:"
          ls -la packages/api/prisma/schema.prisma || echo "Schema not found!"

      - name: Try generating Prisma client
        run: |
          echo "Attempting to generate Prisma client..."
          npm run generate --workspace=@typeamp/api && echo "✅ Prisma generation succeeded!" || echo "❌ Prisma generation failed!"

      - name: Check build scripts
        run: |
          echo "Checking if build commands exist..."
          npm run build --workspace=type --dry-run || echo "Web build script issue"
          npm run build --workspace=@typeamp/api --dry-run || echo "API build script issue"

      - name: Summary
        run: |
          echo "========================================"
          echo "Debug Summary:"
          echo "- Node/npm: Installed"
          echo "- Dependencies: Check above"
          echo "- TypeScript: Check above"
          echo "- Prisma: Check above"
          echo "- Build scripts: Check above"
          echo "========================================"